### ISSUE TITLE
Controlled Modal Opening/Closing

### ISSUE THREAD

**Issue by a-Marino** [redpangilinan/credenza#3]
### Description 
- Propose manual control for modal opening/closing in Credenza.
It would be good to have an isOpen or onClose function to play with the Drawer and Dialog

### Benefits 
- Increased flexibility and control over the interface for users.
- Improved accessibility for users with disabilities.

**Comment by redpangilinan** [comment]
You can actually do that.

This component uses Radix UI under the hood so anything you can do in the Radix UI Dialog Primitive, you can do here as well. Check out the Dialog documentation [here](https://www.radix-ui.com/primitives/docs/components/dialog)

**Comment by a-Marino** [comment]
So open={} onOpenChange={} are available in <Credenza />? my bad didnt know that.
Ty so much!
